name: "Dependency Checks"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  composer-require-checker:
    name: "Composer Require Checker"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          ini-values: memory_limit=-1

      - name: "Install Dependencies"
        uses: "ramsey/composer-install@v2"

      - name: "Set global composer bin-dir"
        run: composer global config bin-dir /usr/local/bin

      - name: "Install require checker"
        run: "composer global require -W maglnet/composer-require-checker"

      - name: "Check"
        run: "/usr/local/bin/composer-require-checker check"

  composer-unused:
    name: "Composer Unused"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          ini-values: memory_limit=-1

      - name: "Install Dependencies"
        uses: "ramsey/composer-install@v2"

      - name: "Set global composer bin-dir"
        run: composer global config bin-dir /usr/local/bin

      - name: "Install Composer Unused"
        run: composer global require icanhazstring/composer-unused

      - name: "Check"
        run: /usr/local/bin/composer-unused
